version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false  # we don't care atm

python:
  install:
    - requirements: docs/requirements.txt
