language: python
sudo: false
cache: pip

env:
# Do not check the most up to date version as it seem to be in compatible with django_nose
#  - DJANGO='https://github.com/django/django/archive/master.tar.gz'
  - DJANGO='django>=2.2.0,<2.3.0'
  - DJANGO='django>=3.0.0,<3.1.0'
  - DJANGO='django>=3.1.0,<3.2.0'

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "nightly"

script:
  coverage run runtests.py


install:
  - travis_retry pip install $DJANGO
  - travis_retry pip install coveralls
  - travis_retry pip install -r test_requirements.txt
  
after_success:
    - coveralls
