language: python
python: 2.7
sudo: false

env:
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py27-django10
    - TOX_ENV=py33-django18
    - TOX_ENV=py34-django18
    - TOX_ENV=py34-django19
    - TOX_ENV=py34-django10

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
