os: linux
arch: arm64-graviton2
virt: lxd
dist: focal
group: edge
language: python
services: postgresql
python:
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'
env:
  - DJANGO=3.2
  - DJANGO=4.0
cache:
- directories:
  - "$TRAVIS_BUILD_DIR/.eggs"
- pip
stages:
- test
jobs:
  fast_finish: true
install:
- travis_retry pip install tox tox-travis
before_script:
- bash ci_setup_postgres.sh
script: tox
after_success:
- bash <(curl -s https://codecov.io/bash)
