# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import quantityfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Megalith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_type', models.CharField(default='Granite', max_length=20)),
                ('weight', quantityfield.fields.QuantityField(base_units='tonnes')),
            ],
        ),
    ]
